### ISSUE TITLE
Remote java udf IndexOutOfBoundsException

### ISSUE THREAD

**Issue by sheltonsuen** [risingwavelabs/arrow-udf#32]
```
[flight-server-default-executor-79] ERROR com.risingwave.functions.UdfServer - Error occurred during UDF execution
java.lang.IndexOutOfBoundsException: index: 512, length: 64 (expected: range(0, 512))
        at org.apache.arrow.memory.ArrowBuf.checkIndex(ArrowBuf.java:701)
        at org.apache.arrow.memory.ArrowBuf.setBytes(ArrowBuf.java:765)
        at org.apache.arrow.vector.BaseLargeVariableWidthVector.setBytes(BaseLargeVariableWidthVector.java:1191)
        at org.apache.arrow.vector.BaseLargeVariableWidthVector.set(BaseLargeVariableWidthVector.java:972)
        at com.risingwave.functions.TypeUtils.fillVector(TypeUtils.java:313)
        at com.risingwave.functions.TypeUtils.createVector(TypeUtils.java:189)
        at com.risingwave.functions.ScalarFunctionBatch.evalBatch(ScalarFunctionBatch.java:56)
        at com.risingwave.functions.UdfProducer.doExchange(UdfProducer.java:89)
        at org.apache.arrow.flight.FlightService.lambda$doExchangeCustom$2(FlightService.java:382)
        at io.grpc.Context$1.run(Context.java:566)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1575)
        Suppressed: java.lang.IllegalStateException: Memory was leaked by query. Memory leaked: (640)
Allocator(exchange) 0/640/640/9223372036854775807 (res/actual/peak/limit)

                at org.apache.arrow.memory.BaseAllocator.close(BaseAllocator.java:477)
                at com.risingwave.functions.UdfProducer.doExchange(UdfProducer.java:79)
                ... 7 more
```

**Comment by sheltonsuen** [comment]
When use java remote udf function, they random failling with those error, not sure if it's apache arrow issue or arrow-udf

**Comment by wangrunji0408** [comment]
It seems like an issue in arrow-udf. Could you provide more context like what the function signature is?
