### ISSUE TITLE
bug: Java UDF Server test failed

### ISSUE THREAD

**Issue by Xuanwo** [risingwavelabs/arrow-udf#41]
https://github.com/risingwavelabs/arrow-udf/actions/runs/9721344803/job/26833892265

```shell
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar (52 kB at 379 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/resolver/maven-resolver-util/1.4.1/maven-resolver-util-1.4.1.jar (168 kB at 1.2 MB/s)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.17s
     Running unittests src/lib.rs (/home/runner/work/arrow-udf/arrow-udf/target/debug/deps/arrow_udf_flight-469f[359](https://github.com/risingwavelabs/arrow-udf/actions/runs/9721344803/job/26833892265#step:9:360)21d5be221)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/flight.rs (/home/runner/work/arrow-udf/arrow-udf/target/debug/deps/flight-3c7bfcf003b9e6b1)

running 7 tests
test test_decimal_add ... FAILED
test test_get_protocol_version ... FAILED
test test_gcd ... FAILED
test test_get ... FAILED
test test_range ... FAILED
test test_json_array_access ... FAILED
test test_list_function ... FAILED

failures:

---- test_decimal_add stdout ----
thread 'test_decimal_add' panicked at arrow-udf-flight/tests/flight.rs:56:53:
called `Result::unwrap()` on an `Err` value: Connect(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_get_protocol_version stdout ----
thread 'test_get_protocol_version' panicked at arrow-udf-flight/tests/flight.rs:130:53:
called `Result::unwrap()` on an `Err` value: Connect(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))))

---- test_gcd stdout ----
thread 'test_gcd' panicked at arrow-udf-flight/tests/flight.rs:28:53:
called `Result::unwrap()` on an `Err` value: Connect(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))))

---- test_get stdout ----
thread 'test_get' panicked at arrow-udf-flight/tests/flight.rs:136:53:
called `Result::unwrap()` on an `Err` value: Connect(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))))

---- test_range stdout ----
thread 'test_range' panicked at arrow-udf-flight/tests/flight.rs:103:53:
called `Result::unwrap()` on an `Err` value: Connect(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))))

---- test_json_array_access stdout ----
thread 'test_json_array_access' panicked at arrow-udf-flight/tests/flight.rs:78:53:
called `Result::unwrap()` on an `Err` value: Connect(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))))

---- test_list_function stdout ----
thread 'test_list_function' panicked at arrow-udf-flight/tests/flight.rs:148:53:
called `Result::unwrap()` on an `Err` value: Connect(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))))


failures:
    test_decimal_add
    test_gcd
    test_get
    test_get_protocol_version
    test_json_array_access
    test_list_function
    test_range

test result: FAILED. 0 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p arrow-udf-flight --test flight`
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/4.0.0/plexus-utils-4.0.0.jar (192 kB at 65 kB/s)
[com.risingwave.functions.TestUdfServer.main()] INFO org.apache.arrow.memory.BaseAllocator - Debug mode disabled. Enable with the VM option -Darrow.memory.debug.allocator=true.
[com.risingwave.functions.TestUdfServer.main()] INFO org.apache.arrow.memory.DefaultAllocationManagerOption - allocation manager type not specified, using netty as the default type
[com.risingwave.functions.TestUdfServer.main()] INFO org.apache.arrow.memory.CheckAllocator - Using DefaultAllocationManager at memory-netty/16.0.0/arrow-memory-netty-16.0.0.jar!/org/apache/arrow/memory/netty/DefaultAllocationManagerFactory.class
[com.risingwave.functions.TestUdfServer.main()] INFO com.risingwave.functions.UdfServer - added function: gcd
[com.risingwave.functions.TestUdfServer.main()] INFO com.risingwave.functions.UdfServer - added function: decimal_add
[com.risingwave.functions.TestUdfServer.main()] INFO com.risingwave.functions.UdfServer - added function: json_array_access
[com.risingwave.functions.TestUdfServer.main()] INFO com.risingwave.functions.UdfServer - added function: return_all
[com.risingwave.functions.TestUdfServer.main()] INFO com.risingwave.functions.UdfServer - added function: return_all_arrays
[com.risingwave.functions.TestUdfServer.main()] INFO com.risingwave.functions.UdfServer - added function: range
[com.risingwave.functions.TestUdfServer.main()] INFO com.risingwave.functions.UdfServer - listening on localhost/127.0.0.1:8815
Error: Process completed with exit code 101.
```

**Comment by Xuanwo** [comment]
Seems a flaky test.

**Comment by wangrunji0408** [comment]
fixed by increasing the waiting time.
